import React from "react";
import "./ClimateIntelligence.css";


const ClimateIntelligence = () => {
  return (
    <div className="ci-container">
      <div className="ci-card">
        <h1>Climate Intelligence Hub 🌍🧠</h1>


        <p>
          This module provides AI-driven insights into climate behavior,
          patterns, and anomaly detection summaries generated by machine
          learning models.
        </p>


        <h2>📊 AI Overview</h2>
        <div className="grid">
          <div className="stat-box">
            <h3>Normal Patterns</h3>
            <p>Stable environmental conditions detected in majority of data.</p>
          </div>


          <div className="stat-box">
            <h3>Anomalies</h3>
            <p>Rare extreme weather events identified using One-Class SVM.</p>
          </div>


          <div className="stat-box">
            <h3>Risk Level</h3>
            <p>Dynamic risk scoring based on temperature, AQI, and humidity.</p>
          </div>


          <div className="stat-box">
            <h3>Data Sources</h3>
            <p>Sensor data, engineered climate dataset, and historical trends.</p>
          </div>
        </div>


        <h2>📈 Key Insights</h2>
        <ul>
          <li>Temperature spikes strongly correlate with anomaly detection</li>
          <li>High AQI levels increase risk classification probability</li>
          <li>Humidity and pressure help stabilize model predictions</li>
          <li>Seasonal patterns improve clustering accuracy</li>
        </ul>


        <h2>🧠 AI Models Used</h2>
        <ul>
          <li>One-Class SVM (Anomaly Detection)</li>
          <li>K-Means Clustering (Climate Profiling)</li>
          <li>StandardScaler (Feature Normalization)</li>
          <li>SHAP (Explainability Layer)</li>
        </ul>


        <div className="footer-note">
          <p>
            Climate Guard AI transforms raw environmental data into actionable
            intelligence for better climate awareness.
          </p>
        </div>
      </div>
    </div>
  );
};


export default ClimateIntelligence;
 

